name: Upload
on:
  push:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - run: npx wrangler pages deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_PAGES_UPLOAD }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
